#release configuration
#Sun May 24 13:20:08 CDT 2026
scm.commentPrefix=[maven-release-plugin] 
exec.pomFileName=pom.xml
pushChanges=false
releaseStrategyId=default
project.scm.net.imagej\:imagej-server.url=https\://github.com/imagej/imagej-server
project.rel.net.imagej\:imagej-server=0.2.0
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
scm.tag=imagej-server-0.2.0
project.dev.net.imagej\:imagej-server=0.2.1-SNAPSHOT
remoteTagging=true
exec.additionalArguments=-Dgpg.skip\=true 
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
projectVersionPolicyId=default
project.scm.net.imagej\:imagej-server.connection=scm\:git\:https\://github.com/imagej/imagej-server
scm.url=scm\:git\:https\://github.com/imagej/imagej-server
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pinExternals=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.snapshotReleasePluginAllowed=false
project.scm.net.imagej\:imagej-server.developerConnection=scm\:git\:git@github.com\:imagej/imagej-server
exec.activateProfiles=deploy-to-scijava
scm.developmentCommitComment=@{prefix} prepare for next development iteration
project.scm.net.imagej\:imagej-server.tag=HEAD
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
completedPhase=end-release
